name: Check for New 1Password SCIM Docker Tags

on:
  schedule:
    - cron: '30 9 * * *'
permissions:
  contents: write
jobs:
  check_for_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag from Docker Hub
        id: get_tag
        run: |
          latest_tag=$(curl -s "https://hub.docker.com/v2/repositories/minio/minio/tags?page_size=1" | jq -r '.results[0].name')
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Read last known tag
        id: last_tag
        run: |
          if [ -f .github/last-minio-tag.txt ]; then
            last_tag=$(cat .github/last-minio-tag.txt)
          else
            last_tag=""
          fi
          echo "last_tag=$last_tag" >> $GITHUB_OUTPUT

      - name: Compare tags and update if needed
        id: update_tag
        run: |
          if [ "${{ steps.get_tag.outputs.latest_tag }}" != "${{ steps.last_tag.outputs.last_tag }}" ]; then
            echo "::set-output name=new_tag::true"
            echo "${{ steps.get_tag.outputs.latest_tag }}" > .github/last-minio-tag.txt
          else
            echo "::set-output name=new_tag::false"
          fi

      - name: Commit updated tag (if new)
        if: steps.update_tag.outputs.new_tag == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .github/last-minio-tag.txt
          git commit -m "Update last seen minio/minio tag"
          git push

      - name: Create issue if new tag found
        if: steps.update_tag.outputs.new_tag == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `New Minio Docker tag: ${{ steps.get_tag.outputs.latest_tag }}`,
              body: `A new tag (${ { steps.get_tag.outputs.latest_tag } }) was found for minio/minio on Docker Hub.`
            })
